import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Header } from '@/components/Header'
import { Top } from '@/components/Top'
import { MenuBar } from '@/components/MenuBar'
import { SNS } from '@/components/SNS'
import { Footer } from '@/components/Footer'
import { ContentConsulting } from '@/components/Content/consulting'

const inter = Inter({ subsets: ['latin'] })

export default function Consulting() {
  return (
    <>
      <Head>
        <title>株式会社MIK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Header/>
      <main className={styles.main}>
        <Top/>
        <MenuBar/>
        <ContentConsulting/>
      </main>
      <Footer/>
      </>
  )
}
