import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Header } from "@/components/Header";
import { Top } from "@/components/Top";
import { MenuBar } from "@/components/MenuBar";
import { ContentMain } from "@/components/Content/main";
import { SNS } from "@/components/Content/sns";
import { Footer } from "@/components/Footer";
import { ContentPeople } from "@/components/Content/people";
import Link from "next/link";
import { SelectContent } from "@/components/Content";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [content, setContent] = useState("");

  const handleClick = (e, id) => {
    setContent(id);
    console.log(id);
  };

  return (
    <>
      <Head>
        <title>株式会社MIK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.main}>
        <Top />
        <MenuBar />
        <SelectContent selected_content={content} />
      </main>
      <Footer />
    </>
  );
}
