import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>株式会社MIK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Image
                  src="/mik_title.svg"
                  alt="mik title Logo"
                  width={488}
                  height={108}
          />
      </header>

      <main className={styles.main}>
        <div className={styles.main_window_back}>
          <Image
              src="/main_window1.svg"
              alt="main title window naritai"
              width={1330}
              height={570}
              className={styles.slider_item}
                      
          />
          <Image
              src="/main_window2.svg"
              alt="main title window naritai"
              width={1330}
              height={570}
              className={styles.slider_item}
           />
          <Image
              src="/main_window3.svg"
              alt="main title window naritai"
              width={1330}
              height={570}
              className={styles.slider_item}
           />
          <Image
              src="/main_window4.svg"
              alt="main title window naritai"
              width={1330}
              height={570}
              className={styles.slider_item}
            />
        </div>

        <div className={styles.main_notice_bottun_back}>
          <div className={styles.notice}>
            <h4>MIKからのお知らせ</h4>
            <ul>
              <li>2023年3月8日　新卒採用説明会開催決定。</li>
              <li>2023年2月16日　新卒採用情報（札幌）をアップしました。</li>
            </ul>

          </div>
          <div className={styles.buttons}>
            <div className={styles.notice_button}>
              <h3>会社資料ダウンロード</h3>
            </div>
            <div className={styles.saiyou_button}>
              <h2>エンジニア採用情報</h2>
            </div>
          </div>
        </div>

        <div className={styles.menu_bar}>
          <ul>
            <li className={styles.menu_tab}>MIKの人々</li>
            <li className={styles.menu_tab}>収入アップ実績</li>
            <li className={styles.menu_tab}>キャリアコンサル</li>
            <li className={styles.menu_tab}>派遣先企業</li>
            <li className={styles.menu_tab}>採用までの流れ</li>
          </ul>

        </div>
        <div className={styles.content_main}>
          <div className={styles.content_main_top}>
            <h1>MIKの特徴</h1>
          </div>

          <div className={styles.content_main_1}>
            <Image
                src="/engineer_first.svg"
                alt="main title window naritai"
                width={682}
                height={301}
                className={styles.content_item1}
              />
              <div className={styles.content_paragragh1}>
              <p>MIKのモットーは、「エンジニア第一主義」。<br/>
                あらゆる交渉面や、サポートにおいて、<br/>
                「エンジニア側」の視点に立って対応します。
              </p>
              </div>
          </div>

          <div className={styles.content_main_2}>
           
              <div className={styles.content_paragragh2}>
              <p>MIKは、あなたがなりたい理想の姿、<br/>
                望ましいワークライフバランス、<br/>
                将来設計など、あなたらしい人生を送ることを重視した<br/>
                「キャリア」の形成を支援します。
              </p>
              </div>
              <Image
                src="/career_image.svg"
                alt="imaging career"
                width={705}
                height={313}
                className={styles.content_item2}
              />
          </div>

          <div className={styles.content_main_3}>
            <Image
                src="/keireki_image.svg"
                alt="main title window naritai"
                width={682}
                height={301}
                className={styles.content_item3}
              />
              <div className={styles.content_paragragh3}>
              <p>MIKには、さまざまな国の方や、<br/>
                あらゆる経歴のエンジニアが多数所属しています。<br/>
                MIKには、従来の「エンジニアの当たり前」をくつがえす<br/>
                「視点」があります。
              </p>
              </div>
          </div>

          <div className={styles.content_main_4}>
           
              <div className={styles.content_paragragh4}>
              <p>MIKでも、多くのエンジニアがリモートワークの現場で活躍しています。<br/>
                リモートワークでも、孤独にならないために、<br/>
                心のケアを含め、<br/>
                さまざまなイベントを実施しています。
              </p>
              </div>
              <Image
                src="/remort_image.svg"
                alt="imaging career"
                width={705}
                height={313}
                className={styles.content_item4}
              />
          </div>
          <div className={styles.content_main_bottom}>
          </div>
         </div>

         <div className={styles.sns_back}>      
          <div className={styles.twitter}>
            <h2>MIK公式twitterアカウント</h2>
          
            <a class="twitter-timeline" href="https://twitter.com/MIK84267256?ref_src=twsrc%5Etfw">Tweets by MIK84267256</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          </div>     

           <div className={styles.line}>

          
             <h2>MIK公式エンジニア採用LINEアカウント</h2>


             <div className={styles.line_content}>
              <Image
                  src="/LINE_Brand_icon.svg"
                  alt="line icon"
                  width={180}
                  height={180}
                  className={styles.line_icon}
                />
                <div className={styles.line_paragrah}>
                  <h4>MIKのキャンペーンや、採用情報も<br/>
                  お友達限定で公開しています！</h4>
                  <p>※社内LINEとは異なる別のアカウントです。
                    MIK社員の方はご注意ください。
                  </p>
                </div>
             
                <Image
                  src="/LINE_QR.svg"
                  alt="line QR code"
                  width={180}
                  height={180}
                  className={styles.line_QR}
                />
               </div>

          </div> 

         </div>
        </main>
        <footer className={styles.footer}>
          <div className={styles.footer_menu}>
          <ul>
            <li>会社情報</li>
            <li>経営理念</li>
            <li>採用情報</li>
            <li>プライバシーポリシ</li>
          </ul>
          </div>

          <div className={styles.company_data}>
            <div className={styles.company_icon}>
            <Image
                    src="/company_name.svg"
                    alt="MIK icon"
                    width={85}
                    height={60}
              />
              </div>
              
              <div className={styles.syozaichi}>
              <p>〒001-0014</p>
              <p>北海道札幌市北区北14条西3丁目2-21<br/>
              小池ビル2F</p>
              <p>TEL 011-299-7361</p>
              </div>
            </div>
          </footer>
    </>
  )
}
