import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>株式会社MIK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Image
                  src="/mik_title.svg"
                  alt="mik title Logo"
                  width={648}
                  height={128}
          />
      </header>

      <main className={styles.main}>
        <div className={styles.main_window_back}>
          <Image
              src="/main_window1.svg"
              alt="main title window naritai"
              width={1230}
              height={520}
              className={styles.slider_item}
                      
          />
          <Image
              src="/main_window2.svg"
              alt="main title window naritai"
              width={1230}
              height={520}
              className={styles.slider_item}
           />
          <Image
              src="/main_window3.svg"
              alt="main title window naritai"
              width={1230}
              height={520}
              className={styles.slider_item}
           />
          <Image
              src="/main_window4.svg"
              alt="main title window naritai"
              width={1230}
              height={520}
              className={styles.slider_item}
            />
        </div>

        <div className={styles.main_notice_bottun_back}>
          <div className={styles.notice}>
            <h4>MIKからのお知らせ</h4>
            <ul>
              <li>2023年3月8日　新卒採用説明会開催決定。</li>
              <li>2023年2月16日　新卒採用情報（札幌）をアップしました。</li>
            </ul>

          </div>
          <div className={styles.buttons}>
            <div className={styles.notice_button}>
              <h2>お問合せ</h2>
            </div>
            <div className={styles.saiyou_button}>
              <h2>エンジニア採用情報</h2>
            </div>
          </div>
        </div>

        <div className={styles.menu_bar}>
          <ul>
            <li className={styles.menu_tab}>MIKの人々</li>
            <li className={styles.menu_tab}>収入アップ実績</li>
            <li className={styles.menu_tab}>キャリアコンサル</li>
            <li className={styles.menu_tab}>派遣先企業</li>
            <li className={styles.menu_tab}>採用までの流れ</li>
          </ul>

        </div>


      </main>
    </>
  )
}
