import Head from "next/head";

export default function HeadElement(props) {

  return (

      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maxmum-scale=1.0, user-scalable=no" />
        <link rel="icon" href="/mik_fabicon.png" />
      </Head>
  );
}
