import Head from "next/head";

export default function HeadElement(props) {
  return (
    <Head>
      <title>{props.title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maxmum-scale=1.0, user-scalable=no"
      />
      <link rel="icon" href="/mik_fabicon.png" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@300;400&display=swap" rel="stylesheet"
      />
    </Head>
  );
}
