const ADD_INFO = "ADD_INFO";

export const addInfo = (obj) => {
  return {
    type: ADD_INFO,
    payload: { obj },
  };
};

const INFOS = [
  {
    name_sei: "",
    name_mei: "",
    name_sei_kana: "",
    name_mei_kana: "",
    mail: "",
    confirm_mail: "",
    gender: "",
    birth_year: "",
    birth_month: "",
    birth_day: "",
    post_code: "",
    address: "",
    phone: "",
    work_experience: "",
    job_change_experience: "",
    it: "",
    freelance: "",
    last_experience: "",
    last_company: "",
    experienced_skill: "",
    qualification: {
      it_pass: false,
      kihon: false,
      ouyou: false,
      network_specialist: false,
      data_specialist: false,
      anzenkakuho: false,
      ipa_other: false,
      ipa_other_qualification: "",
      cloud_practitioner: false,
      developer_associate: false,
      SAA: false,
      sysopes: false,
      devops: false,
      SAP: false,
      advanced_networking: false,
      data_analytics: false,
      database_specialty: false,
      machine_learning: false,
      security_specialty: false,
      sap_on_aws: false,
      aws_other: false,
      aws_other_qualification: "",
      linuc_1: false,
      linuc_2: false,
      linuc_3: false,
      lpic_1: false,
      lpic_2: false,
      lpic_3: false,
      ccna: false,
      ccnp: false,
      cct: false,
      ccie: false,
      oracle_bronze: false,
      oracle_silver: false,
      oracle_gold: false,
      oracle_platinum: false,
      azure_fundamentals: false,
      azure_administrator: false,
      ms_other: false,
      ms_other_qualification: "",
      comptia_cloud: false,
      comptia_network: false,
      comptia_other: false,
      comptia_other_qualification: "",
    },
    experienced_language: {
      ruby: false,
      swift: false,
      php: false,
      html_css: false,
      go: false,
      sql: false,
      perl: false,
      kotolin: false,
      cobol: false,
      c_prus: false,
      c_sharp: false,
      python: false,
      java: false,
      javascript: false,
    },
  },
];

export const infoReducer = (state = INFOS, action) => {
  switch (action.type) {
    case ADD_INFO: {
      console.log(action.payload.obj);

      if (!action.payload) {
        return state;
      }
      const newInfo = {
        name_sei: action.payload.obj.name_sei,
        name_mei: action.payload.obj.name_mei,
        name_sei_kana: action.payload.obj.name_sei_kana,
        name_mei_kana: action.payload.obj.name_mei_kana,
        mail: action.payload.obj.mail,
        gender: action.payload.obj.gender,
        birth_year: action.payload.obj.birth_year,
        birth_month: action.payload.obj.birth_month,
        birth_day: action.payload.obj.birth_day,
        post_code: action.payload.obj.post_code,
        address: action.payload.obj.address,
        phone: action.payload.obj.phone,
        work_experience: action.payload.obj.work_experience,
        job_change_experience: action.payload.obj.job_change_experience,
        it: action.payload.obj.it,
        freelance: action.payload.obj.freelance,
        experienced_skill: action.payload.obj.experienced_skill,
        qualification: {
          it_pass: action.payload.obj.qualification.it_pass,
          kihon: action.payload.obj.qualification.kihon,
          ouyou: action.payload.obj.qualification.ouyou,
          network_specialist: action.payload.obj.qualification.network_specialist,
          data_specialist:action.payload.obj.qualification.data_specialist,
          anzenkakuho: action.payload.obj.qualification.anzenkakuho,
          ipa_other: action.payload.obj.qualification.ipa_other,
          ipa_other_qualification: action.payload.obj.qualification.ipa_other_qualification,
          cloud_practitioner: action.payload.obj.qualification.cloud_practitioner,
          developer_associate: action.payload.obj.qualification.developer_associate,
          SAA: action.payload.obj.qualification.SAA,
          sysopes: action.payload.obj.qualification.sysopes,
          devops: action.payload.obj.qualification.devops,
          SAP: action.payload.obj.qualification.SAP,
          advanced_networking: action.payload.obj.qualification.advanced_networking,
          data_analytics:action.payload.obj.qualification.data_analytics,
          database_specialty: action.payload.obj.qualification.database_specialty,
          machine_learning: action.payload.obj.qualification.machine_learning,
          security_specialty:action.payload.obj.qualification.security_specialty,
          sap_on_aws: action.payload.obj.qualification.sap_on_aws,
          aws_other: action.payload.obj.qualification.aws_other,
          aws_other_qualification: action.payload.obj.qualification.aws_other_qualification,
          linuc_1: action.payload.obj.qualification.linuc_1,
          linuc_2: action.payload.obj.qualification.linuc_2,
          linuc_3: action.payload.obj.qualification.linuc_3,
          lpic_1: action.payload.obj.qualification.lpic_1,
          lpic_2: action.payload.obj.qualification.lpic_2,
          lpic_3: action.payload.obj.qualification.lpic_3,
          ccna: action.payload.obj.qualification.ccna,
          ccnp: action.payload.obj.qualification.ccnp,
          cct: action.payload.obj.qualification.cct,
          ccie: action.payload.obj.qualification.ccie,
          oracle_bronze: action.payload.obj.qualification.oracle_bronze,
          oracle_silver: action.payload.obj.qualification.oracle_silver,
          oracle_gold: action.payload.obj.qualification.oracle_gold,
          oracle_platinum: action.payload.obj.qualification.oracle_platinum,
          azure_fundamentals: action.payload.obj.qualification.azure_fundamentals,
          azure_administrator: action.payload.obj.qualification.azure_administrator,
          ms_other: action.payload.obj.qualification.ms_other,
          ms_other_qualification: action.payload.obj.qualification.ms_other_qualification,
          comptia_cloud: action.payload.obj.qualification.comptia_cloud,
          comptia_network: action.payload.obj.qualification.comptia_network,
          comptia_other:action.payload.obj.qualification.comptia_other,
          comptia_other_qualification: action.payload.obj.qualification.comptia_other_qualification,
        },
        experienced_language: {
          ruby: action.payload.obj.experienced_language.ruby,
          swift: action.payload.obj.experienced_language.swift,
          php:action.payload.obj.experienced_language.php,
          html_css: action.payload.obj.experienced_language.html_css,
          go: action.payload.obj.experienced_language.go,
          sql: action.payload.obj.experienced_language.sql,
          perl: action.payload.obj.experienced_language.perl,
          kotolin: action.payload.obj.experienced_language.kotolin,
          cobol: action.payload.obj.experienced_language.cobol,
          c_prus: action.payload.obj.experienced_language.c_prus,
          c_sharp:action.payload.obj.experienced_language.c_sharp,
          python: action.payload.obj.experienced_language.python,
          java: action.payload.obj.experienced_language.java,
          javascript: action.payload.obj.experienced_language.javascript
        },
      
      };

      return [...state, newInfo];
    }
    default: {
      return state;
    }
  }
};
